import type { ExportVerbosity, GlitchProject } from "./types";
import type { DisplayUnit } from "./units";

function formatNumber(value: number): string {
  return Number.isInteger(value) ? `${value}` : value.toFixed(6);
}

function buildParameterBlock(project: GlitchProject): string {
  const effectiveSourceHz =
    project.clock.clkSrc === "pll" ? project.clock.pllFrequencyHz : project.clock.sourceFrequencyHz;
  const cycleNs = 1e9 / effectiveSourceHz;
  const stepNs = cycleNs / project.clock.phaseShiftSteps;
  const degPerStep = 360 / project.clock.phaseShiftSteps;

  return [
    "# Generated by Glitch Visualizer (simulation-first)",
    `# glitch_source_hz=${formatNumber(effectiveSourceHz)} (clk_src=${project.clock.clkSrc})`,
    `# cycle_ns=${formatNumber(cycleNs)}, step_ns=${formatNumber(stepNs)}, deg_per_step=${formatNumber(degPerStep)}`,
    "scope.glitch.enabled = True",
    `scope.glitch.clk_src = '${project.clock.clkSrc}'`,
    `scope.clock.fpga_vco_freq = ${formatNumber(project.clock.fpgaVcoFrequencyHz)}`,
    `scope.glitch.output = '${project.glitch.outputMode}'`,
    `scope.glitch.trigger_src = '${project.trigger.triggerSource}'`,
    `scope.glitch.arm_timing = '${project.trigger.armTiming}'`,
    `scope.glitch.offset = ${project.glitch.offsetSteps}`,
    `scope.glitch.width = ${project.glitch.widthSteps}`,
    `scope.glitch.num_glitches = ${project.glitch.numGlitches}`,
    `scope.glitch.repeat = ${JSON.stringify(project.glitch.repeat)}`,
    `scope.glitch.ext_offset = ${JSON.stringify(project.glitch.extOffset)}`,
    `scope.io.glitch_hp = ${project.glitch.hpEnabled ? "True" : "False"}`,
    `scope.io.glitch_lp = ${project.glitch.lpEnabled ? "True" : "False"}`,
  ].join("\n");
}

export function generatePythonExport(
  project: GlitchProject,
  verbosity: ExportVerbosity,
  displayUnit: DisplayUnit = "steps",
): string {
  if (project.glitch.outputMode === "crowbar_visualizer") {
    return [
      "# WARNING: 'crowbar_visualizer' is a UI-only visualization mode.",
      "# No Python export is generated for this mode.",
      "# Switch Output Mode to a real Husky option (clock_xor, clock_or, glitch_only, clock_only, enable_only).",
    ].join("\n");
  }

  const params = buildParameterBlock(project);
  const displayNote =
    displayUnit !== "steps"
      ? `# NOTE: UI currently displaying in ${displayUnit}; exported values are native Husky steps.\n`
      : "";

  if (verbosity === "params_only") {
    return displayNote ? `${displayNote}${params}` : params;
  }

  return [
    "import chipwhisperer as cw",
    "",
    `# Full stub export from Glitch Visualizer${displayNote ? `\n${displayNote.trimEnd()}` : ""}`,
    "scope = cw.scope()",
    "target = cw.target(scope)",
    "",
    params,
    "",
    "assert scope.glitch.mmcm_locked",
    "print('Configured glitch module successfully.')",
    "print('actual_num_glitches=', getattr(scope.glitch, 'actual_num_glitches', 'n/a'))",
  ].join("\n");
}
